
#File: .github/workflows/workflow.yml

on:
  push:
    branches:
      - main

name: AzureLoginSample

jobs:

  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    
    - uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    
    - run: |
        az webapp list --query "[?state=='Running']"
       
    - name: Create Resource Group
      run: |
        az group create --name tudorDevopsProject --location northeurope
        az webapp list --query "[?state=='Running']"
        
    - name: Create Web App
      run: |
        az webapp create --name tudorApp --resource-group tudorDevopsProject --plan myplan --runtime "NODE|14-lts" --deployment-local-git

    
