
#File: .github/workflows/workflow.yml

on:
  push:
    branches:
      - main

name: AzureLoginSample

jobs:

  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    
    - uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    
    - run: |
        az webapp list --query "[?state=='Running']"
       
    - name: Create Resource Group
      run: |
        az group create --name tudorDevopsProject --location northeurope
        az webapp list --query "[?state=='Running']"
        
    - name: Create Web App
      run: |
        az webapp create --name tudorApp --resource-group tudorDevopsProject --plan tudorPlan --runtime "NODE|14-lts" --deployment-local-git

    - name: Create SQL Server
      run: |
        az sql server create --name tudorSQLServer --resource-group tudorDevopsProject --location northeurope --admin-user myadmin --admin-password AdminPassword1234!@#$
    
    - name: Create Firewall Rule
      run: |
        az sql server firewall-rule create --name AllowAllWindowsAzureIps --resource-group tudorDevopsProject --server tudorSQLServer --start-ip-address 0.0.0.0 --end-ip-address 0.0.0.0
    
    - name: Create SQL Database
      run: |
        az sql db create --name tudorDatabase --resource-group tudorDevopsProject --server tudorSQLServer --tier Basic --edition Basic --collation SQL_Latin1_General_CP1_CI_AS

    #This command creates an autoscale setting for the tudorApp web app. It specifies that the app should have at least 1 instance, at most 5 instances, and maintain an average CPU utilization of 70% over a 5-minute period. It also specifies that the time grain for evaluating the condition should be 5 minutes. You can adjust these values to suit your needs.
    - name: Create Autoscale settings
      run: |
        az monitor autoscale create --resource-group tudorDevopsProject --resource tudorApp --resource-type Microsoft.Web/sites --name tudorAutoscale --min-count 1 --max-count 3 --count 2
